const { exec } = require("child_process");
const fs = require("fs");
const path = require("path");
const dotenv = require("dotenv");
const { format } = require("prettier");

dotenv.config({ path: [".env.local", ".env.test", ".env"] });

const generateTypes = async () => {
  const typesPath = path.resolve(__dirname, "../src/lib/supabase/types.ts");
  const DATABASE_URL = process.env.DATABASE_URL;
  if (!DATABASE_URL) {
    console.error("DATABASE_URL not found in .env");
    return;
  }
  exec(
    `npx supabase gen types typescript --db-url ${DATABASE_URL}`,
    (err, stdout, stderr) => {
      if (err) {
        console.error(err);
        return;
      }

      const generatedTypes = `
    // This file is auto-generated by scripts/gen-types.js
    // Do not modify this file directly

    ${stdout}
    `;

      format(generatedTypes, { parser: "typescript" })
        .then((formattedTypes) => {
          fs.writeFileSync(path.resolve(__dirname, typesPath), formattedTypes);
          console.log("\x1b[32m Types generated successfully!!!");
        })
        .catch((err) => {
          console.error(err);
        });
    }
  );
};

generateTypes();
