on:
  pull_request:
    types: [converted_to_draft]

jobs:
  move-asana-task-to-in-progress:
    runs-on: ubuntu-latest
    name: Move Asana task to code In progress section
    steps:
      - name: Move Asana task to in progress section
        uses: everphone-gmbh/github-asana-action@c4d0c3aeb4768dc9dc45fb60b843c0510da20dd5
        with:
          asana-pat: ${{ secrets.ASANA_PAT }}
          action: "move-section"
          targets: '[{"project": "teamzy", "section": "In progress"}]'
